default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: root
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: db_centro_nutricao_development

# production:
#   <<: *default
#   database: db_raira_nutricionista_production

# test:
#   <<: *default
#   database: db_raira_nutricionista_test