ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.irregular 'funcao', 'funcoes'
  inflect.irregular 'texto_live', 'textos_livres'
  inflect.irregular 'imagem_cabec', 'imagens_cabec'
  inflect.irregular 'fornecedor', 'fornecedores'
  inflect.irregular 'cabec', 'cabecs'
  inflect.irregular 'convenio', 'convenios'
  inflect.irregular 'conselho_regional', 'conselho_regionais'
  inflect.irregular 'profissional', 'profissionais'
  inflect.irregular 'centro_de_custo', 'centro_de_custos'
  inflect.irregular 'historico', 'historicos'
  inflect.irregular 'permissao', 'permissoes'
  inflect.irregular 'empresa_permissao', 'empresa_permissoes'
  inflect.irregular 'usuario_permissao', 'usuario_permissoes'
  inflect.irregular 'agenda_movimentacao', 'agenda_movimentacoes'
end
